import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <Link href="/b7r" passHref>
            <h1>Go to b7r</h1>
          </Link>
        </h1>
        <h1>
          <Link href="/plavit"passHref>
            <h1>Go to plavit</h1>
          </Link>
        </h1>
      </main>
    </div>
  );
}
